@ScholarshipPlatform_HostAddress = http://localhost:5274

### USERS

POST {{ScholarshipPlatform_HostAddress}}/users
Content-Type: application/json

{
    "Name": "Rufino Américo",
    "Email": "rufino@gmail.com",
    "Password": "Rufino@0",
    "GPA": 10,
    "BirthDate": "1999-11-11"
}

###

GET {{ScholarshipPlatform_HostAddress}}/users/2

###

GET {{ScholarshipPlatform_HostAddress}}/users

###

PATCH {{ScholarshipPlatform_HostAddress}}/users/2
Content-Type: application/json

{
    "Name": "    Lucas Isaac Cassoma"
}

###

DELETE {{ScholarshipPlatform_HostAddress}}/users/2

### SCHOLARSHIPS

POST {{ScholarshipPlatform_HostAddress}}/scholarships
Content-Type: application/json

{
    "Name": "Türkiye Scholarships",
    "Description": "Türkiye Scholarships is a government-funded scholarship program for international students.",
    "Deadline": "2026-12-12",
    "Eligibility": "Minimum Academic Achievement\n\n- For associate and bachelor's degree candidates: 70%\n- For graduate candidates: 75%\n- For candidates of Health Sciences (Medicine, Dentistry and Pharmacy): 90%\n\nAge Criteria\n\n- For associate and bachelor's degree programmes: Under 21 years of age.\n- For master's programs: under 30 years of age.\n- For PhD programs: under 35 years of age.\n- For Research Scholarship: under 50 years of age.",
    "HowToApply": "Visit the official website or register for our mentorship program so that we can guide you.",
    "OfficialUrl": "https://www.turkiyeburslari.gov.tr/",
    "RequiredDocuments": "- ID or passport\n- A photograph of the candidate taken within the last 1 year\n- Transcript\n- Diploma"
}

###

GET {{ScholarshipPlatform_HostAddress}}/scholarships/2
###
GET {{ScholarshipPlatform_HostAddress}}/scholarships

###

PATCH {{ScholarshipPlatform_HostAddress}}/scholarships/1
Content-Type: application/json

{
    "Name": "Türkiye Scholarships 2",
    "Eligibility": "Minimum Academic Achievement\n\n- For associate and bachelor's degree candidates: 70%\n- For graduate candidates: 75%\n- For candidates of Health Sciences (Medicine, Dentistry and Pharmacy): 90%\n\nAge Criteria\n\n- For associate and bachelor's degree programmes: Under 21 years of age.\n- For master's programs: under 30 years of age.\n- For PhD programs: under 35 years of age.\n- For Research Scholarship: under 50 years of age.",
    "HowToApply": "Visit the official website or register for our mentorship program so that we can guide you.",
    "OfficialUrl": "https://www.turkiyeburslari.gov.tr/",
    "RequiredDocuments": "- ID or passport\n- A photograph of the candidate taken within the last 1 year\n- Transcript\n- Diploma"
}
###
DELETE {{ScholarshipPlatform_HostAddress}}/scholarships/1

### SCHOLARSHIP APPLICATIONS

POST {{ScholarshipPlatform_HostAddress}}/scholarshipApplications
Content-Type: application/json

{
    "UserId": 1,
    "ScholarshipId": 2
}

###

GET {{ScholarshipPlatform_HostAddress}}/scholarshipApplications/1

###

GET {{ScholarshipPlatform_HostAddress}}/scholarshipApplications

###

PATCH {{ScholarshipPlatform_HostAddress}}/scholarshipApplications/1
Content-Type: application/json

{
    "Status": "ApprOveD"
}

###

DELETE {{ScholarshipPlatform_HostAddress}}/scholarshipApplications/1