@ScholarshipPlatform_HostAddress = http://localhost:5274

###GET  {{ScholarshipPlatform_HostAddress}}/test-email

### USERS

POST {{ScholarshipPlatform_HostAddress}}/users
Content-Type: application/json

{
    "Name": "Mentorando2",
    "Email": "mentorando2@gmail.com",
    "Password": "Mentorando2@0",
    "GPA": 15,
    "BirthDate": "2004-11-11"
}

###

POST {{ScholarshipPlatform_HostAddress}}/users/login
Content-Type: application/json

{
    "Email": "Mentordabolsa@gmail.com",
    "Password": "Mentordabolsa@0"
}

###

GET {{ScholarshipPlatform_HostAddress}}/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0IiwiZW1haWwiOiJSdWZpbm9AZ21haWwuY29tIiwibmFtZSI6IlJ1ZmlubyBBbcOpcmljbyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6Ik1lbnRvcmFuZG8iLCJleHAiOjE3ODk0ODM1MjIsImlzcyI6IlNjaG9sYXJzaGlwUGxhdGZvcm0iLCJhdWQiOiJTY2hvbGFyc2hpcFBsYXRmb3JtIn0.n_bs5QIdOSHQ7MGFc6T36srVag3Tw2eMC_br_8kzyNk

###

GET {{ScholarshipPlatform_HostAddress}}/users/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1IiwiZW1haWwiOiJNZW50b3JkYWJvbHNhQGdtYWlsLmNvbSIsIm5hbWUiOiJNZW50b3IgZGEgQm9sc2EiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJNZW50b3IiLCJleHAiOjE3ODk0ODM2MDksImlzcyI6IlNjaG9sYXJzaGlwUGxhdGZvcm0iLCJhdWQiOiJTY2hvbGFyc2hpcFBsYXRmb3JtIn0.ZcVNvNbqooNPuP0gg6V8jTVmDm3EZDIke2p-AxZzQiY

###

GET {{ScholarshipPlatform_HostAddress}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1IiwiZW1haWwiOiJNZW50b3JkYWJvbHNhQGdtYWlsLmNvbSIsIm5hbWUiOiJNZW50b3IgZGEgQm9sc2EiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJNZW50b3IiLCJleHAiOjE3ODk0ODM2MDksImlzcyI6IlNjaG9sYXJzaGlwUGxhdGZvcm0iLCJhdWQiOiJTY2hvbGFyc2hpcFBsYXRmb3JtIn0.ZcVNvNbqooNPuP0gg6V8jTVmDm3EZDIke2p-AxZzQiY

###
PATCH {{ScholarshipPlatform_HostAddress}}/users/Rufino@gmail.com/reactivate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3IiwiZW1haWwiOiJjYXNzb21hQGdtYWlsLmNvbSIsIm5hbWUiOiJjYXNzb21hIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3ODk0ODI5NTAsImlzcyI6IlNjaG9sYXJzaGlwUGxhdGZvcm0iLCJhdWQiOiJTY2hvbGFyc2hpcFBsYXRmb3JtIn0.TMFHkiW84bXAipYz2zMlpR6k44nEzYnpgeXuKfxYfhY

###
PATCH {{ScholarshipPlatform_HostAddress}}/users/Rufino@gmail.com/suspend
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3IiwiZW1haWwiOiJjYXNzb21hQGdtYWlsLmNvbSIsIm5hbWUiOiJjYXNzb21hIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3ODk0ODI5NTAsImlzcyI6IlNjaG9sYXJzaGlwUGxhdGZvcm0iLCJhdWQiOiJTY2hvbGFyc2hpcFBsYXRmb3JtIn0.TMFHkiW84bXAipYz2zMlpR6k44nEzYnpgeXuKfxYfhY

###

PATCH {{ScholarshipPlatform_HostAddress}}/users/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3IiwiZW1haWwiOiJjYXNzb21hQGdtYWlsLmNvbSIsIm5hbWUiOiJjYXNzb21hIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3ODk0NDU2NjgsImlzcyI6IlNjaG9sYXJzaGlwUGxhdGZvcm0iLCJhdWQiOiJTY2hvbGFyc2hpcFBsYXRmb3JtIn0.svcbyQCRqN1wl8NnqSeeEE43-TdFnPOBCk7qWWfwvVU
Content-Type: application/json

{
    "Name": "Americo"
}

###

PATCH {{ScholarshipPlatform_HostAddress}}/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiZW1haWwiOiJNYW51ZWxAZ21haWwuY29tIiwibmFtZSI6Ik1hbnVlbCBGdXhpIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiTWVudG9yYW5kbyIsImV4cCI6MTc4OTM1MzEzNCwiaXNzIjoiU2Nob2xhcnNoaXBQbGF0Zm9ybSIsImF1ZCI6IlNjaG9sYXJzaGlwUGxhdGZvcm0ifQ.ISTU8Tu_eY56wslJzlwr4CWSrg1J00R2dV1jtKMQJok
Content-Type: application/json

{
    "Name": "    Lucas Isaac"
}

###

DELETE {{ScholarshipPlatform_HostAddress}}/users/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3IiwiZW1haWwiOiJjYXNzb21hQGdtYWlsLmNvbSIsIm5hbWUiOiJjYXNzb21hIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3ODk0ODI5NTAsImlzcyI6IlNjaG9sYXJzaGlwUGxhdGZvcm0iLCJhdWQiOiJTY2hvbGFyc2hpcFBsYXRmb3JtIn0.TMFHkiW84bXAipYz2zMlpR6k44nEzYnpgeXuKfxYfhY

### SCHOLARSHIPS

POST {{ScholarshipPlatform_HostAddress}}/scholarships
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3IiwiZW1haWwiOiJjYXNzb21hQGdtYWlsLmNvbSIsIm5hbWUiOiJjYXNzb21hIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3ODkzNTMwMTAsImlzcyI6IlNjaG9sYXJzaGlwUGxhdGZvcm0iLCJhdWQiOiJTY2hvbGFyc2hpcFBsYXRmb3JtIn0.gaSBHqkMfQQpnkN2sFoP43N--QhVpTPo_ObUUG82_8Y
Content-Type: application/json

{
    "Name": "Bolsa Roménia",
    "Description": "Bolsa Unilab is a government-funded scholarship program for international students.",
    "Deadline": "2026-12-12",
    "Eligibility": "Minimum Academic Achievement\n\n- For associate and bachelor's degree candidates: 70%\n- For graduate candidates: 75%\n- For candidates of Health Sciences (Medicine, Dentistry and Pharmacy): 90%\n\nAge Criteria\n\n- For associate and bachelor's degree programmes: Under 21 years of age.\n- For master's programs: under 30 years of age.\n- For PhD programs: under 35 years of age.\n- For Research Scholarship: under 50 years of age.",
    "HowToApply": "Visit the official website or register for our mentorship program so that we can guide you.",
    "OfficialUrl": "https://www.turkiyeburslari.gov.tr/",
    "RequiredDocuments": "- ID or passport\n- A photograph of the candidate taken within the last 1 year\n- Transcript\n- Diploma"
}

###

GET {{ScholarshipPlatform_HostAddress}}/scholarships
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiZW1haWwiOiJNYW51ZWxAZ21haWwuY29tIiwibmFtZSI6Ik1hbnVlbCBGdXhpIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiTWVudG9yYW5kbyIsImV4cCI6MTc4OTM1MzEzNCwiaXNzIjoiU2Nob2xhcnNoaXBQbGF0Zm9ybSIsImF1ZCI6IlNjaG9sYXJzaGlwUGxhdGZvcm0ifQ.ISTU8Tu_eY56wslJzlwr4CWSrg1J00R2dV1jtKMQJok

###
GET {{ScholarshipPlatform_HostAddress}}/scholarships

###

PATCH {{ScholarshipPlatform_HostAddress}}/scholarships/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3IiwiZW1haWwiOiJjYXNzb21hQGdtYWlsLmNvbSIsIm5hbWUiOiJjYXNzb21hIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3ODkzNTMwMTAsImlzcyI6IlNjaG9sYXJzaGlwUGxhdGZvcm0iLCJhdWQiOiJTY2hvbGFyc2hpcFBsYXRmb3JtIn0.gaSBHqkMfQQpnkN2sFoP43N--QhVpTPo_ObUUG82_8Y
Content-Type: application/json

{
    "Name": "Unilab Bolsa",
    "Eligibility": "Minimum Academic Achievement\n\n- For associate and bachelor's degree candidates: 70%\n- For graduate candidates: 75%\n- For candidates of Health Sciences (Medicine, Dentistry and Pharmacy): 90%\n\nAge Criteria\n\n- For associate and bachelor's degree programmes: Under 21 years of age.\n- For master's programs: under 30 years of age.\n- For PhD programs: under 35 years of age.\n- For Research Scholarship: under 50 years of age.",
    "HowToApply": "Visit the official website or register for our mentorship program so that we can guide you.",
    "OfficialUrl": "",
    "RequiredDocuments": "- ID or passport\n- A photograph of the candidate taken within the last 1 year\n- Transcript\n- Diploma"
}
###
DELETE {{ScholarshipPlatform_HostAddress}}/scholarships/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3IiwiZW1haWwiOiJjYXNzb21hQGdtYWlsLmNvbSIsIm5hbWUiOiJjYXNzb21hIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3ODkzNTMwMTAsImlzcyI6IlNjaG9sYXJzaGlwUGxhdGZvcm0iLCJhdWQiOiJTY2hvbGFyc2hpcFBsYXRmb3JtIn0.gaSBHqkMfQQpnkN2sFoP43N--QhVpTPo_ObUUG82_8Y

### SCHOLARSHIP APPLICATIONS

POST {{ScholarshipPlatform_HostAddress}}/scholarshipApplications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1IiwiZW1haWwiOiJNZW50b3JkYWJvbHNhQGdtYWlsLmNvbSIsIm5hbWUiOiJNZW50b3IgZGEgQm9sc2EiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJNZW50b3IiLCJleHAiOjE3ODkzNTI2MzMsImlzcyI6IlNjaG9sYXJzaGlwUGxhdGZvcm0iLCJhdWQiOiJTY2hvbGFyc2hpcFBsYXRmb3JtIn0.L_fIF_tBVvgPMUAp_oB_0O017vdWRlgW6dursxNuo20
Content-Type: application/json

{
    "UserId": 4,
    "ScholarshipId": 4
}

###

GET {{ScholarshipPlatform_HostAddress}}/scholarshipApplications/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1IiwiZW1haWwiOiJNZW50b3JkYWJvbHNhQGdtYWlsLmNvbSIsIm5hbWUiOiJNZW50b3IgZGEgQm9sc2EiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJNZW50b3IiLCJleHAiOjE3ODkzNTI2MzMsImlzcyI6IlNjaG9sYXJzaGlwUGxhdGZvcm0iLCJhdWQiOiJTY2hvbGFyc2hpcFBsYXRmb3JtIn0.L_fIF_tBVvgPMUAp_oB_0O017vdWRlgW6dursxNuo20

###
GET {{ScholarshipPlatform_HostAddress}}/scholarshipApplications/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3IiwiZW1haWwiOiJjYXNzb21hQGdtYWlsLmNvbSIsIm5hbWUiOiJjYXNzb21hIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3ODk0MDY4OTcsImlzcyI6IlNjaG9sYXJzaGlwUGxhdGZvcm0iLCJhdWQiOiJTY2hvbGFyc2hpcFBsYXRmb3JtIn0.up-s28z3m5sgvGUK895UzvI9en-amzHBFD2KrM58-sk
###
GET {{ScholarshipPlatform_HostAddress}}/scholarshipApplications/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3IiwiZW1haWwiOiJjYXNzb21hQGdtYWlsLmNvbSIsIm5hbWUiOiJjYXNzb21hIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3ODk0MDY4OTcsImlzcyI6IlNjaG9sYXJzaGlwUGxhdGZvcm0iLCJhdWQiOiJTY2hvbGFyc2hpcFBsYXRmb3JtIn0.up-s28z3m5sgvGUK895UzvI9en-amzHBFD2KrM58-sk

###

PATCH {{ScholarshipPlatform_HostAddress}}/scholarshipApplications/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1IiwiZW1haWwiOiJNZW50b3JkYWJvbHNhQGdtYWlsLmNvbSIsIm5hbWUiOiJNZW50b3IgZGEgQm9sc2EiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJNZW50b3IiLCJleHAiOjE3ODkzNTI2MzMsImlzcyI6IlNjaG9sYXJzaGlwUGxhdGZvcm0iLCJhdWQiOiJTY2hvbGFyc2hpcFBsYXRmb3JtIn0.L_fIF_tBVvgPMUAp_oB_0O017vdWRlgW6dursxNuo20
Content-Type: application/json

{
    "Status": "Rejected"
}

###

DELETE {{ScholarshipPlatform_HostAddress}}/scholarshipApplications/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3IiwiZW1haWwiOiJjYXNzb21hQGdtYWlsLmNvbSIsIm5hbWUiOiJjYXNzb21hIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3ODkzNTMwMTAsImlzcyI6IlNjaG9sYXJzaGlwUGxhdGZvcm0iLCJhdWQiOiJTY2hvbGFyc2hpcFBsYXRmb3JtIn0.gaSBHqkMfQQpnkN2sFoP43N--QhVpTPo_ObUUG82_8Y


### PAYMENTS

POST {{ScholarshipPlatform_HostAddress}}/payments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3IiwiZW1haWwiOiJjYXNzb21hQGdtYWlsLmNvbSIsIm5hbWUiOiJjYXNzb21hIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3ODk0ODI5NTAsImlzcyI6IlNjaG9sYXJzaGlwUGxhdGZvcm0iLCJhdWQiOiJTY2hvbGFyc2hpcFBsYXRmb3JtIn0.TMFHkiW84bXAipYz2zMlpR6k44nEzYnpgeXuKfxYfhY
Content-Type: application/json

{
    "Amount": 1000,
    "BillingPeriod": "2026-08-01",
    "UserEmail": "Rufino@gmail.com"
}

###
GET {{ScholarshipPlatform_HostAddress}}/payments/unpaid
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3IiwiZW1haWwiOiJjYXNzb21hQGdtYWlsLmNvbSIsIm5hbWUiOiJjYXNzb21hIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3ODk0ODI5NTAsImlzcyI6IlNjaG9sYXJzaGlwUGxhdGZvcm0iLCJhdWQiOiJTY2hvbGFyc2hpcFBsYXRmb3JtIn0.TMFHkiW84bXAipYz2zMlpR6k44nEzYnpgeXuKfxYfhY

###

GET {{ScholarshipPlatform_HostAddress}}/payments/previous-period
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3IiwiZW1haWwiOiJjYXNzb21hQGdtYWlsLmNvbSIsIm5hbWUiOiJjYXNzb21hIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3ODk0ODI5NTAsImlzcyI6IlNjaG9sYXJzaGlwUGxhdGZvcm0iLCJhdWQiOiJTY2hvbGFyc2hpcFBsYXRmb3JtIn0.TMFHkiW84bXAipYz2zMlpR6k44nEzYnpgeXuKfxYfhY

###
GET {{ScholarshipPlatform_HostAddress}}/payments/user/Rufino@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3IiwiZW1haWwiOiJjYXNzb21hQGdtYWlsLmNvbSIsIm5hbWUiOiJjYXNzb21hIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3ODk0ODI5NTAsImlzcyI6IlNjaG9sYXJzaGlwUGxhdGZvcm0iLCJhdWQiOiJTY2hvbGFyc2hpcFBsYXRmb3JtIn0.TMFHkiW84bXAipYz2zMlpR6k44nEzYnpgeXuKfxYfhY
